name: Sequential Job execution
on: push
jobs:
  test:
    runs-on: ubuntu-24.04 
    steps:
      - name: Print greeting message
        run: echo "Hello World, welcome to year 2025.."
      - name: Print Signing off
        run: echo "Done"
  dev:
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - name: Get system information
        run: |
          echo "Jobs are running on `hostname -f` "
          echo "Current kernel version is `uname -r` "
          echo "Current date and time is `date` "
          echo "You are working as `whoami` user"
