name: Multi Job Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-24.04 # ubuntu-latest
    steps:
      - name: Print greeting message
        run: echo "Hello World, welcome to year 2025.."
      - name: Print Signing off
        run: echo "Done"
  dev:
    runs-on: ubuntu-24.04
    steps:
      - name: Get system information
        run: |
          - echo "Current date and time is `date` "
          - echo "You are working as `whoami` user"
